"""empty message

Revision ID: 1147f0db73b0
Revises: 30404264d6c4
Create Date: 2015-12-02 14:19:17.148094

"""

# revision identifiers, used by Alembic.
revision = '1147f0db73b0'
down_revision = '30404264d6c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
