"""empty message

Revision ID: 17215eafe5cb
Revises: 2e3dffd965b9
Create Date: 2015-12-03 11:50:30.362609

"""

# revision identifiers, used by Alembic.
revision = '17215eafe5cb'
down_revision = '2e3dffd965b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
