"""empty message

Revision ID: 18c53bd8f446
Revises: 51320b7548b5
Create Date: 2016-01-12 11:24:23.053122

"""

# revision identifiers, used by Alembic.
revision = '18c53bd8f446'
down_revision = '51320b7548b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
