"""empty message

Revision ID: 1c611c1f9885
Revises: 24588efadc8e
Create Date: 2015-12-09 13:59:17.103403

"""

# revision identifiers, used by Alembic.
revision = '1c611c1f9885'
down_revision = '24588efadc8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('species_ibfk_2', 'species', ['iucn_status_id'], unique=False)
    op.create_index('species_ibfk_1', 'species', ['esa_status_id'], unique=False)
    op.drop_column('source_types', 'database_id')
    ### end Alembic commands ###
