"""empty message

Revision ID: 1f972cdd61aa
Revises: 4d22b29c1a58
Create Date: 2015-12-03 10:07:23.987846

"""

# revision identifiers, used by Alembic.
revision = '1f972cdd61aa'
down_revision = '4d22b29c1a58'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.create_index('ix_growth_forms_raunkiaer_id', 'growth_forms_raunkiaer', ['id'], unique=False)
    op.create_index('ix_populations_id', 'populations', ['id'], unique=False)
    op.create_index('ix_reproductive_repetition_id', 'reproductive_repetition', ['id'], unique=False)
    op.create_index('ix_stage_types_id', 'stage_types', ['id'], unique=False)
    op.create_index('ix_stages_id', 'stages', ['id'], unique=False)
    op.create_index('ix_treatment_types_id', 'treatment_types', ['id'], unique=False)
    op.create_index('ix_treatments_id', 'treatments', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatments_id', 'treatments')
    op.drop_index('ix_treatment_types_id', 'treatment_types')
    op.drop_index('ix_stages_id', 'stages')
    op.drop_index('ix_stage_types_id', 'stage_types')
    op.drop_index('ix_reproductive_repetition_id', 'reproductive_repetition')
    op.drop_index('ix_populations_id', 'populations')
    op.drop_index('ix_growth_forms_raunkiaer_id', 'growth_forms_raunkiaer')
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body_html', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
