"""empty message

Revision ID: 20ef9847e948
Revises: 20f6b2e8fef7
Create Date: 2016-01-12 10:31:08.136180

"""

# revision identifiers, used by Alembic.
revision = '20ef9847e948'
down_revision = '20f6b2e8fef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
