"""empty message

Revision ID: 20f6b2e8fef7
Revises: 33444b034cf6
Create Date: 2016-01-12 10:30:32.340543

"""

# revision identifiers, used by Alembic.
revision = '20f6b2e8fef7'
down_revision = '33444b034cf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
