"""empty message

Revision ID: 2463c3d630f5
Revises: 1c611c1f9885
Create Date: 2015-12-09 14:09:01.634936

"""

# revision identifiers, used by Alembic.
revision = '2463c3d630f5'
down_revision = '1c611c1f9885'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_missing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missing_data_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['missing_data_id'], ['missing_data.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('species_ibfk_2', 'species', ['iucn_status_id'], unique=False)
    op.create_index('species_ibfk_1', 'species', ['esa_status_id'], unique=False)
    op.drop_table('publication_purposes')
    op.drop_table('publication_missing_data')
    ### end Alembic commands ###
