"""empty message

Revision ID: 25cd9d8d4e43
Revises: 4188b309c94f
Create Date: 2015-12-09 12:00:09.968090

"""

# revision identifiers, used by Alembic.
revision = '25cd9d8d4e43'
down_revision = '4188b309c94f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('species_ibfk_2', 'species', ['iucn_status_id'], unique=False)
    op.create_index('species_ibfk_1', 'species', ['esa_status_id'], unique=False)
    ### end Alembic commands ###
