"""empty message

Revision ID: 2b69dec6f1b0
Revises: 26b39b8868a4
Create Date: 2015-12-15 15:56:41.448566

"""

# revision identifiers, used by Alembic.
revision = '2b69dec6f1b0'
down_revision = '26b39b8868a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
