"""empty message

Revision ID: 2d6275c53403
Revises: 20ef9847e948
Create Date: 2016-01-12 10:31:14.893078

"""

# revision identifiers, used by Alembic.
revision = '2d6275c53403'
down_revision = '20ef9847e948'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
