"""empty message

Revision ID: 2e3dffd965b9
Revises: 39b8d80967a
Create Date: 2015-12-03 11:50:21.609125

"""

# revision identifiers, used by Alembic.
revision = '2e3dffd965b9'
down_revision = '39b8d80967a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esa_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=64), nullable=True),
    sa.Column('status_name', sa.String(length=64), nullable=True),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_esa_statuses_status_code', 'esa_statuses', ['status_code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_esa_statuses_status_code', 'esa_statuses')
    op.drop_table('esa_statuses')
    ### end Alembic commands ###
