"""empty message

Revision ID: 2fb91ef61a2a
Revises: 2463c3d630f5
Create Date: 2015-12-09 14:09:24.275697

"""

# revision identifiers, used by Alembic.
revision = '2fb91ef61a2a'
down_revision = '2463c3d630f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('species_ibfk_1', 'species')
    op.drop_index('species_ibfk_2', 'species')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('species_ibfk_2', 'species', ['iucn_status_id'], unique=False)
    op.create_index('species_ibfk_1', 'species', ['esa_status_id'], unique=False)
    ### end Alembic commands ###
