"""empty message

Revision ID: 30404264d6c4
Revises: 51f5ccfba190
Create Date: 2015-12-02 14:17:39.446081

"""

# revision identifiers, used by Alembic.
revision = '30404264d6c4'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
