"""empty message

Revision ID: 33444b034cf6
Revises: e5d904ec758
Create Date: 2016-01-12 10:28:42.905946

"""

# revision identifiers, used by Alembic.
revision = '33444b034cf6'
down_revision = 'e5d904ec758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('matrices_ibfk_9', 'matrices')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('matrices_ibfk_9', 'matrices', ['treatment_id'], unique=False)
    ### end Alembic commands ###
