"""empty message

Revision ID: 357a13a7be5f
Revises: 1f972cdd61aa
Create Date: 2015-12-03 10:21:30.466659

"""

# revision identifiers, used by Alembic.
revision = '357a13a7be5f'
down_revision = '1f972cdd61aa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatments_id', 'treatments')
    op.drop_index('ix_treatment_types_id', 'treatment_types')
    op.drop_index('ix_stages_id', 'stages')
    op.drop_index('ix_stage_types_id', 'stage_types')
    op.add_column('species', sa.Column('user_modified', mysql.INTEGER(display_width=11), nullable=True))
    op.add_column('species', sa.Column('user_created', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('species', 'user_modified_id')
    op.drop_column('species', 'user_created_id')
    op.drop_index('ix_reproductive_repetition_id', 'reproductive_repetition')
    op.drop_index('ix_populations_id', 'populations')
    op.drop_index('ix_growth_forms_raunkiaer_id', 'growth_forms_raunkiaer')
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body_html', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
