"""empty message

Revision ID: 360f43276f49
Revises: 3ff815ee4186
Create Date: 2016-01-12 09:48:19.354398

"""

# revision identifiers, used by Alembic.
revision = '360f43276f49'
down_revision = '3ff815ee4186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
