"""empty message

Revision ID: 3646995d9e9b
Revises: 2fb91ef61a2a
Create Date: 2015-12-15 15:34:48.443277

"""

# revision identifiers, used by Alembic.
revision = '3646995d9e9b'
down_revision = '2fb91ef61a2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrices', sa.Column('matrix_a_string', sa.Text(), nullable=True))
    op.add_column('matrices', sa.Column('matrix_class_string', sa.Text(), nullable=True))
    op.drop_index('species_ibfk_2', 'species')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('species_ibfk_2', 'species', ['iucn_status_id'], unique=False)
    op.drop_column('matrices', 'matrix_class_string')
    op.drop_column('matrices', 'matrix_a_string')
    ### end Alembic commands ###
