"""empty message

Revision ID: 39b8d80967a
Revises: 4cb234befb1d
Create Date: 2015-12-03 10:28:44.519161

"""

# revision identifiers, used by Alembic.
revision = '39b8d80967a'
down_revision = '4cb234befb1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
