"""empty message

Revision ID: 3c0ea234e245
Revises: 2d6275c53403
Create Date: 2016-01-12 10:31:32.669258

"""

# revision identifiers, used by Alembic.
revision = '3c0ea234e245'
down_revision = '2d6275c53403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
