"""empty message

Revision ID: 3ff815ee4186
Revises: None
Create Date: 2016-01-07 11:53:29.894077

"""

# revision identifiers, used by Alembic.
revision = '3ff815ee4186'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
