"""empty message

Revision ID: 41bffcdf1764
Revises: 3646995d9e9b
Create Date: 2015-12-15 15:34:55.567337

"""

# revision identifiers, used by Alembic.
revision = '41bffcdf1764'
down_revision = '3646995d9e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
