"""empty message

Revision ID: 49ceafad332d
Revises: d3f31b9407a
Create Date: 2015-12-16 13:37:57.760432

"""

# revision identifiers, used by Alembic.
revision = '49ceafad332d'
down_revision = 'd3f31b9407a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
