"""empty message

Revision ID: 4cb234befb1d
Revises: 357a13a7be5f
Create Date: 2015-12-03 10:23:25.715226

"""

# revision identifiers, used by Alembic.
revision = '4cb234befb1d'
down_revision = '357a13a7be5f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'user_created')
    op.drop_column('species', 'user_modified')
    op.create_index('ix_stage_types_id', 'stage_types', ['id'], unique=False)
    op.create_index('ix_stages_id', 'stages', ['id'], unique=False)
    op.create_index('ix_treatment_types_id', 'treatment_types', ['id'], unique=False)
    op.create_index('ix_treatments_id', 'treatments', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatments_id', 'treatments')
    op.drop_index('ix_treatment_types_id', 'treatment_types')
    op.drop_index('ix_stages_id', 'stages')
    op.drop_index('ix_stage_types_id', 'stage_types')
    op.add_column('species', sa.Column('user_modified', mysql.INTEGER(display_width=11), nullable=True))
    op.add_column('species', sa.Column('user_created', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
