"""empty message

Revision ID: 51320b7548b5
Revises: 3c0ea234e245
Create Date: 2016-01-12 11:24:09.947251

"""

# revision identifiers, used by Alembic.
revision = '51320b7548b5'
down_revision = '3c0ea234e245'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('species_accepted', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'species_accepted')
    ### end Alembic commands ###
