"""empty message

Revision ID: ab494bd8ad2
Revises: 49ceafad332d
Create Date: 2016-01-07 11:53:22.952293

"""

# revision identifiers, used by Alembic.
revision = 'ab494bd8ad2'
down_revision = '49ceafad332d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
