"""empty message

Revision ID: d3f31b9407a
Revises: 28ca0d70327c
Create Date: 2015-12-16 13:37:54.290571

"""

# revision identifiers, used by Alembic.
revision = 'd3f31b9407a'
down_revision = '28ca0d70327c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_class_info_bussys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_class_info_id', sa.Integer(), nullable=True),
    sa.Column('bussys_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bussys_id'], ['bussys.id'], ),
    sa.ForeignKeyConstraint(['stage_class_info_id'], ['stage_class_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bussys_matrix_id', 'bussys', ['matrix_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bussys_matrix_id', 'bussys')
    op.drop_table('stage_class_info_bussys')
    ### end Alembic commands ###
