"""empty message

Revision ID: e5d904ec758
Revises: 360f43276f49
Create Date: 2016-01-12 09:48:27.983831

"""

# revision identifiers, used by Alembic.
revision = 'e5d904ec758'
down_revision = '360f43276f49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
